package com.compraventa.entidades;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */

@Entity
@Table(name="categoria")
public class Categoria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name="idcategoria", nullable= false)	
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int idcategoria;	
	
	@Column(name="nomcategoria", nullable= false)
	private String nomcategoria;
	
	@Column(name="descripcion", nullable= false)
	private String descripcion;


	@OneToMany(cascade=CascadeType.ALL)
	@JoinColumn(name="idcategoria")
	private List<Productos> producto;
	
	@OneToMany(cascade=CascadeType.ALL)
	@JoinColumn(name="idcategoria")
	private List<Subcategoria> subcategoria;

	public int getIdcategoria() {
		return this.idcategoria;
	}

	public void setIdcategoria(int idcategoria) {
		this.idcategoria = idcategoria;
	}
	

	public String getNomcategoria() {
		return this.nomcategoria;
	}

	public void setNomcategoria(String nomcategoria) {
		this.nomcategoria = nomcategoria;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	

}
