package com.compraventa.entidades;

import java.sql.Blob;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.format.annotation.DateTimeFormat;



/**
 * Productos generated by hbm2java
 */

@Entity
@Table(name="productos")
public class Productos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name="idproducto", nullable= false)	
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int idproducto;
	
	@ManyToOne(optional=false)
	@JoinColumn(name = "idseccion", nullable = false)
	private Seccion seccion;
	
	@ManyToOne(optional=false)
	@JoinColumn(name = "idcategoria", nullable = false)
	private Categoria categoria;
	
	@ManyToOne(optional=false)
	@JoinColumn(name = "idsubcategoria", nullable = false)
	private Subcategoria subcategoria;
	
	@Column(name="titulo", nullable= false)
	@NotEmpty(message = "El titulo es un campo obligatorio")	
	private String titulo;	
	
	@Column(name="precio", nullable= false)
	@NotNull(message = "El precio es un campo obligatorio")	
	private Double precio;
	
	@Column(name="fechaPublicacion", nullable= false)	
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@NotNull(message = "La fecha es un campo obligatorio")
	private Date fechaPublicacion;
	
	@Column(name="estado", nullable= false)
	@NotEmpty(message = "El estado del producto es obligatorio")	
	private String estado;
	
	@Column(name="visitas", nullable= false)
	private Integer visitas;
	
	@Column(name="nomImagen", nullable= false)
	@NotEmpty(message = "El nombre de la imagen es obligatorio")	
	private String nomImagen;
	
	@Lob	
	@Column(name="urlFoto1", nullable= false)	
	private java.sql.Blob urlFoto1;	

	public Productos() {
	}

	

	public int getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(int idproducto) {
		this.idproducto = idproducto;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}


	public Subcategoria getSubcategoria() {
		return subcategoria;
	}



	public void setSubcategoria(Subcategoria subcategoria) {
		this.subcategoria = subcategoria;
	}



	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}	

	public String getNomImagen() {
		return nomImagen;
	}

	public void setNomImagen(String nomImagen) {
		this.nomImagen = nomImagen;
	}

	public Double getPrecio() {
		return this.precio;
	}

	public void setPrecio(Double precio) {
		this.precio = precio;
	}

	public Date getFechaPublicacion() {
		return this.fechaPublicacion;
	}

	public void setFechaPublicacion(Date fechaPublicacion) {
		this.fechaPublicacion = fechaPublicacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Integer getVisitas() {
		return this.visitas;
	}

	public void setVisitas(Integer visitas) {
		this.visitas = visitas;
	}	
	
	public Blob getUrlFoto1() {
		return urlFoto1;
	}

	public void setUrlFoto1(Blob urlFoto1) {
		this.urlFoto1 = urlFoto1;
	}
	
	public Seccion getSeccion() {
		return seccion;
	}

	public void setSeccion(Seccion seccion) {
		this.seccion = seccion;
	}

}
