package com.compraventa.entidades;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subcategoria generated by hbm2java
 */

@Entity
@Table(name="subcategoria")
public class Subcategoria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name="idsubcategoria", nullable= false)	
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int idsubcategoria;	

	@Column(name="nomsubcategoria", nullable= false)
	private String nomsubcategoria;
	
	@ManyToOne(optional=false)
	@JoinColumn(name = "idcategoria", nullable = false)
	private Categoria categoria;
	
	@OneToMany(cascade=CascadeType.ALL)
	@JoinColumn(name="idsubcategoria")
	private List<Productos> producto;
	
	

	public Subcategoria() {
	}
	

	public int getIdsubcategoria() {
		return this.idsubcategoria;
	}

	public void setIdsubcategoria(int idsubcategoria) {
		this.idsubcategoria = idsubcategoria;
	}

	public String getNomsubcategoria() {
		return this.nomsubcategoria;
	}

	public void setNomsubcategoria(String nomsubcategoria) {
		this.nomsubcategoria = nomsubcategoria;
	}

	public Categoria getCategoria() {
		return categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}
	
	

	

}
