package com.compraventa.entidades;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.format.annotation.DateTimeFormat;


/**
 * Usuarios generated by hbm2java
 */

@Entity
@Table(name="usuarios")
public class Usuarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;	
	
	private int idusuario;	
	
	private String nombre;	
	
	private String apellidos;	
	
	private String email;	
	
	private Integer edad;	
	
	private String tlf;	
	
	private String fotoUrl;	
	
	private String registrado;
	
	private String clave;	
	
	private Date reg_Date;	

	
	public Usuarios() {
		
	}

	@Id
	@Column(name="idusuario", nullable= false)	
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name="nombre", nullable= false)
	@NotEmpty(message = "El nombre es obligatorio")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	@Column(name="apellidos")
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name="email", nullable= false)
	@NotEmpty(message = "El email es obligatorio")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name="edad")
	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	@Column(name="tlf")
	public String getTlf() {
		return this.tlf;
	}

	public void setTlf(String tlf) {
		this.tlf = tlf;
	}
	@Column(name="fotoUrl")
	public String getFotoUrl() {
		return this.fotoUrl;
	}

	public void setFotoUrl(String fotoUrl) {
		this.fotoUrl = fotoUrl;
	}
	@Column(name="registrado")
	public String getRegistrado() {
		return this.registrado;
	}

	public void setRegistrado(String registrado) {
		this.registrado = registrado;
	}

	@Column(name="clave")
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="reg_date")
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	public Date getReg_Date() {
		return reg_Date;
	}


	public void setReg_Date(Date reg_Date) {
		this.reg_Date = reg_Date;
	}

	

}
